import { StyleSheet } from "react-native";

export default StyleSheet.create({
    headerContainer:{
        padding:10,
        backgroundColor:'#e0e0e0'
    },
    txtJobDetail:{
        alignSelf:'center',
        fontSize:18,
        color:'black',
        fontWeight:'bold'
    },
    InfoContent:{
        padding:10,
    },
    rowInfo:{
        flexDirection:'row'
    },
    txtName:{
        tintColor:'black',
        marginVertical:5,
        color:'black',
        fontWeight:'bold',
        fontSize:20
    },
    txtLocation:{
        color:'#ab000d',
        fontSize:15,
        fontWeight:'bold'
    },
    txtLevel:{
        color:'#ab000d',
        fontSize:15,
        fontWeight:'bold'
    },
    txtLocationInner:{
        color:'black'
    },
    txtLevelInner:{
        color:'black'
    },
    btns:{
        padding:10,
        flexDirection:'row',
        alignSelf:'center'
    },
    btnSubmit:{
        padding:10,
        paddingHorizontal:40,
        fontWeight:'bold',
        backgroundColor:'#b71c1c',
        color:'white',
        fontSize:20,
        marginHorizontal:10,
        borderRadius:12
    },
    btnFavorite:{
        padding:10,
        paddingHorizontal:40,
        backgroundColor:'#b71c1c',
        color:'white',
        fontSize:18,
        marginHorizontal:10,
        borderRadius:12
    }
})